version: '3'
services:

  #PHP 7.3
  #php:
  #  restart: always
  #  build: ./.docker/php7.3
  #  volumes:
  #    - ./www:/var/www/:consistent
  #    - ./.docker/php7.3/log:/var/log/
  #  depends_on:
  #    - postgresql

  #PHP 8.0.9
  php:
    restart: always
    build: ./.docker/php8.0.9
    volumes:
      - ./www:/var/www/:consistent
      - ./.docker/php8.0.9/log:/var/log/
      - ./.docker/php8.0.9/conf.d/php-project.ini:/usr/local/etc/php/conf.d/php-project.ini
    depends_on:
      - postgresql

  postgresql:
    image: postgres:13-alpine
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRESQL_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRESQL_PASSWORD}
      - POSTGRES_DB=${POSTGRESQL_DATABASE}
    ports:
      - ${POSTGRESQL_PORT}:5432
    volumes:
      - ./.docker/postgresql/data:/var/lib/postgresql/data:consistent

  #adminer:
  #  image: adminer
  #  restart: always
  #  ports:
  #    - ${ADMINER_PORT}:8080
  #  depends_on:
  #    - postgresql

  nginx:
    build: .docker/nginx
    restart: always
    ports:
      - ${NGINX_PORT}:80
    volumes:
      - ./www:/var/www:consistent
      - ./.docker/nginx/logs:/var/log/nginx
      - ./.docker/nginx/conf.d:/etc/nginx/conf.d/
      - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php